name: Update README Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare assets folder
        shell: bash
        run: |
          mkdir -p assets

      - name: Download stats SVGs
        shell: bash
        run: |
          USERNAME=oandremotta
          THEME=github_dark

          curl -L "https://github-readme-stats.vercel.app/api?username=${USERNAME}&show_icons=true&theme=${THEME}&hide_border=true&cache_seconds=86400" -o assets/github-stats.svg
          curl -L "https://github-readme-stats.vercel.app/api/top-langs/?username=${USERNAME}&layout=compact&theme=${THEME}&hide_border=true&cache_seconds=86400" -o assets/top-langs.svg

      - name: Commit & push if changed
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add assets/github-stats.svg assets/top-langs.svg

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update readme stats"
            git push
          fi
